# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '___PROJECTNAME___' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ___PROJECTNAME___

  # ignore all warnign
  inhibit_all_warnings!

  # Network
  pod 'Alamofire'
  pod 'RxAlamofire'

  # Reactive Programming
  pod 'RxSwift'

  target '___PROJECTNAME___Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '___PROJECTNAME___UITests' do
    # Pods for testing
  end

end
